;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; DEFAULT POOL (fallback / unknown hosts)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[www]
user = www-data
group = www-data
listen = 9000
pm = ondemand
pm.max_children = 3
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 2
pm.process_idle_timeout = 20s
pm.max_requests = 400
php_admin_value[open_basedir] = /var/www/:/global/:/tmp/
clear_env = no
catch_workers_output = yes
request_terminate_timeout = 60s
